### ISSUE TITLE
이런 오류는 어떻게해야하나요?

### ISSUE THREAD

**Issue by YourHeadIs** [CrackThrough/ADOFAI-Mod-Installation-Guide#2]
[Player.log](https://github.com/CrackThrough/ADOFAI-Mod-Installation-Guide/files/6403399/Player.log)

**Comment by CrackThrough** [comment]
제가 요즘 다른 일에 바빠서 issue 확인을 잘 못하고 있습니다. 모딩 커뮤니티 디스코드를 이용해주시길 바랍니다.
절대 디렉토리 이름에 한글이 들어가면 안됩니다.
